name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]  # 监听主分支提交
  pull_request: {}              # 监听 PR

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 设置 Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 缓存依赖
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]  
          pip install build twine

      # 运行测试
      - name: Run tests
        run: |
          pytest -v --cov=your_package tests/

      # 构建包
      - name: Build package
        run: python -m build
        if: github.ref == 'refs/heads/master'  
        # 仅主分支构建